package com.example.gameword.utils

enum class Password {
    PASSWORD_MATCHED,
    PASSWORD_NOT_MATCHED,
    PASSWORDS_FIELDS_EMPTY,
    PASSWORD_LESS_THAN_EIGHT_CHARACTERS,
    CONFIRM_PASSWORD_LESS_THAN_EIGHT_CHARACTERS,
    BOTH_LESS_THAN_8_CHARACTERS
}